    ### Основные настройки ###

# Токен дискорд-бота
token: put_here_your_token

# ID сервера. Его можно посмотреть в настройках
serverId: 123

# Если стоит значение true, то бот сможет кикать пользователей с него
allowKick: true

    ### Названия каналов и ролей ###

  ## Каналы ##
# В этот канал отправляются списки зарандомленных людей
main: main

# Этот канал используется для управления ботом с помощью команд
control: control

# В этот канал пользователи вводят свои ники
whitelist: whitelist

  ## Роли ##
# Роль человека, выбранного рандомом с помощью команды add
picked: picked

# Роль человека, вписавшего свой ник в whitelist
participant: participant

# Список ролей, исключенных из рандома
excluded:
  - MVP+
  - БОСС

    ### Рандомные сообщения ###
messages:
  - "привет фывфыв я в дс но не на серве добавишь в вайт лист?? я ждал 68 часов и не успел го перенабор пожалуйста!!! почему я в дс но не могу писать в вайтлист что мне делать??? эм я зашел на в дс , но у меня нет роли закинь в гч съемки пожалуйста!! привет фывфыв добавь в друзья вк прошууу . закрепи этот комментарий если любишь подписчиков. эмммм привет фывфыв я упал в самом начале го второй шанс пж..."
  - "*ввввд-жуужу-жббжжужу*\nРобот запущен. Рандом начинается!"