name: Aegis
version: 1.0
author: 7isenko
main: io.github._7isenko.aegis.Aegis
api-version: 1.12
commands:
  event:
    description: Starts or stops your discord bot. "kick" kicks every member without role from discord.
    usage: /event start, /event stop, /event kick
    permission: aegis.usage
permissions:
  aegis.usage:
    description: allows to use this plugin
    default: op